services:
  exemple_clickhouse:
    image: ${CLICKHOUSE_IMAGE}
    container_name: ${CLICKHOUSE_CONTAINER_NAME}
    hostname: ${CLICKHOUSE_HOSTNAME}
    networks:
      - exemple_network
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
      - "${CLICKHOUSE_TCP_PORT}:9000"
    volumes:
      - clickhouse_db:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    stop_grace_period: 1m

networks:
  exemple_network:
    external: true

volumes:
  clickhouse_db:
    driver: local